### ISSUE TITLE
你好，AdaptivePose++的代码何时能提交呢

### ISSUE THREAD

**Issue by yzew** [buptxyb666/AdaptivePose#1]

**Comment by buptxyb666** [comment]
目前已经是AdaptivePose++的代码了，可以复现coco和crowdpose的结果

**Comment by yzew** [comment]
> 目前已经是AdaptivePose++的代码了，可以复现coco和crowdpose的结果

好的谢谢。我尝试用四张2080Ti来训练这个模型，但一个epoch要训练100min，这是正常的么

**Comment by buptxyb666** [comment]
你的model，input resolution和batch size分别是什么，HRNet-W48和800 pixel 在八卡V100上一个epoch大概25分钟。

**Comment by buptxyb666** [comment]
小模型10分钟
