### ISSUE TITLE
src/lib/models/predictor.py   

### ISSUE THREAD

**Issue by suijua** [buptxyb666/AdaptivePose#13]
![image](https://user-images.githubusercontent.com/98210579/224999872-aaf52557-4c97-4685-9097-17be3e7f4925.png)

您好！我很好奇src/lib/models/predictor.py  133行代码 为何不是返回 offset，而是offset1?

**Comment by buptxyb666** [comment]
kps就是两跳偏移相加得到的中心到关键点的offset，offset1是第一跳偏移，用于可视化自适应点位置

**Comment by suijua** [comment]
> kps就是两跳偏移相加得到的中心到关键点的offset，offset1是第一跳偏移，用于可视化自适应点位置
好的，非常感谢！
