### ISSUE TITLE
No such file or directory: '/home/aa/AdaptivePose-master/src/lib/../../exp/multi_pose_wodet/hrnet_48_coco640/model_last.pth'

### ISSUE THREAD

**Issue by yzew** [buptxyb666/AdaptivePose#3]
您好，请问通过bash main_hrnet48_coco640.sh，一开始训练就报错FileNotFoundError: [Errno 2] No such file or directory: '/home/aa/AdaptivePose-master/src/lib/../../exp/multi_pose_wodet/hrnet_48_coco640/model_last.pth'是什么原因，这不应该是在训练一轮后生成的么？训练的时候已经吧main_hrnet48_coco640.sh中的测试部分注释掉了。

**Comment by buptxyb666** [comment]
这块脚本有些问题，去掉--resume就ok了
